language: android

sudo: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
  - chmod +x install-cmake.sh
  - ./install-cmake.sh -d

script: ./gradlew build ./gradlew connectedAndroidTest